---
abstract: 'create sets of colours.'
author:
  - 'Kathryn Andersen'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Graphics-Colourset
provides:
  Graphics::Colourset:
    file: lib/Graphics/Colourset.pm
    version: '0.04'
requires:
  Getopt::ArgvFile: '1.09'
  Getopt::Long: '2.34'
  Graphics::ColorObject: '0'
  Pod::Usage: '0'
resources:
  homepage: http://github.com/rubykat/Graphics-Colourset
  repository: git://github.com/rubykat/Graphics-Colourset.git
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
